# Generated by Django 5.2.7 on 2025-12-03 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LivestockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='畜種名')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '畜種マスタ',
                'verbose_name_plural': '畜種マスタ',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分類名')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '分類マスタ',
                'verbose_name_plural': '分類マスタ',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='メーカー名')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'メーカーマスタ',
                'verbose_name_plural': 'メーカーマスタ',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='商品番号')),
                ('product_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='商品コード')),
                ('livestock_type', models.CharField(max_length=50, verbose_name='畜種')),
                ('category', models.CharField(max_length=100, verbose_name='分類')),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名')),
                ('model_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='型式')),
                ('specification', models.CharField(blank=True, max_length=200, null=True, verbose_name='規格')),
                ('shipping_unit', models.CharField(max_length=50, verbose_name='発送単位')),
                ('shipping_fee', models.CharField(blank=True, max_length=100, null=True, verbose_name='送料')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('status', models.CharField(choices=[('active', '有効'), ('pending', '申請中'), ('inactive', '無効')], default='active', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('bigram_keywords', models.TextField(blank=True, null=True, verbose_name='Bigramキーワード')),
                ('sort_num', models.IntegerField(blank=True, null=True, verbose_name='並び順')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products_master.manufacturer', verbose_name='メーカー')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['sort_num', 'livestock_type', 'category', 'manufacturer', 'product_name'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year_month', models.CharField(max_length=6, verbose_name='適用開始年月')),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='卸売価格')),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='参考小売価格')),
                ('kenren_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='県連価格')),
                ('gross_margin_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='粗利率')),
                ('revision_reason', models.TextField(blank=True, null=True, verbose_name='改定理由')),
                ('status', models.CharField(choices=[('active', '有効'), ('pending', '申請中'), ('approved', '承認済み'), ('rejected', '却下'), ('inactive', '無効')], default='active', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
                ('applicant', models.CharField(blank=True, max_length=100, null=True, verbose_name='申請者')),
                ('approver', models.CharField(blank=True, max_length=100, null=True, verbose_name='承認者')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='承認日時')),
                ('sort_num', models.IntegerField(blank=True, null=True, verbose_name='並び順')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_histories', to='products_master.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '価格履歴',
                'verbose_name_plural': '価格履歴',
                'ordering': ['-start_year_month'],
                'unique_together': {('product', 'start_year_month')},
            },
        ),
        migrations.CreateModel(
            name='ProductApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_type', models.CharField(choices=[('create', '新規作成'), ('update', '更新'), ('delete', '削除')], max_length=10, verbose_name='承認種別')),
                ('status', models.CharField(choices=[('pending', '申請中'), ('approved', '承認済み'), ('rejected', '却下')], default='pending', max_length=20, verbose_name='承認ステータス')),
                ('applicant', models.CharField(max_length=100, verbose_name='申請者')),
                ('application_date', models.DateTimeField(auto_now_add=True, verbose_name='申請日時')),
                ('approver', models.CharField(blank=True, max_length=100, null=True, verbose_name='承認者')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='承認日時')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='却下理由')),
                ('changes_json', models.TextField(blank=True, null=True, verbose_name='変更内容JSON')),
                ('product_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='商品番号')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products_master.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品承認',
                'verbose_name_plural': '商品承認',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistoryApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_type', models.CharField(choices=[('create', '新規作成'), ('update', '更新'), ('delete', '削除')], max_length=10, verbose_name='承認種別')),
                ('status', models.CharField(choices=[('pending', '申請中'), ('approved', '承認済み'), ('rejected', '却下')], default='pending', max_length=20, verbose_name='承認ステータス')),
                ('applicant', models.CharField(max_length=100, verbose_name='申請者')),
                ('application_date', models.DateTimeField(auto_now_add=True, verbose_name='申請日時')),
                ('approver', models.CharField(blank=True, max_length=100, null=True, verbose_name='承認者')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='承認日時')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='却下理由')),
                ('start_year_month', models.CharField(blank=True, max_length=6, null=True, verbose_name='適用開始年月')),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='卸売価格')),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='参考小売価格')),
                ('kenren_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='県連価格')),
                ('gross_margin_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='粗利率')),
                ('revision_reason', models.TextField(blank=True, null=True, verbose_name='改定理由')),
                ('is_delete_request', models.BooleanField(default=False, verbose_name='削除申請フラグ')),
                ('price_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products_master.pricehistory', verbose_name='価格履歴')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_master.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '価格履歴承認',
                'verbose_name_plural': '価格履歴承認',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductGrossMarginRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_margin_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='粗利率')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products_master.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品粗利率',
                'verbose_name_plural': '商品粗利率',
            },
        ),
        migrations.CreateModel(
            name='AiExtractTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='取引ID')),
                ('pdf_file_path', models.CharField(max_length=500, verbose_name='PDFファイルパス')),
                ('status', models.CharField(choices=[('processing', '処理中'), ('completed', '完了'), ('error', 'エラー')], default='processing', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='エラーメッセージ')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備考')),
            ],
            options={
                'verbose_name': 'AI抽出取引',
                'verbose_name_plural': 'AI抽出取引',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AiExtractTransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_text', models.TextField(verbose_name='抽出テキスト')),
                ('product_candidates', models.TextField(blank=True, null=True, verbose_name='商品候補JSON')),
                ('selected_product_id', models.IntegerField(blank=True, null=True, verbose_name='選択商品ID')),
                ('extracted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='抽出価格')),
                ('extracted_start_month', models.CharField(blank=True, max_length=6, null=True, verbose_name='抽出開始月')),
                ('status', models.CharField(choices=[('pending', '未処理'), ('matched', 'マッチ済み'), ('skipped', 'スキップ')], default='pending', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('selected_candidate_text', models.TextField(blank=True, null=True, verbose_name='選択候補テキスト')),
                ('extracted_revision_reason', models.TextField(blank=True, null=True, verbose_name='抽出改定理由')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='products_master.aiextracttransaction', verbose_name='取引')),
            ],
            options={
                'verbose_name': 'AI抽出取引詳細',
                'verbose_name_plural': 'AI抽出取引詳細',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(help_text='YYYY/MM形式', max_length=7, verbose_name='対象年月')),
                ('pdf_file_path', models.CharField(max_length=500, verbose_name='PDFファイルパス')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('uploaded_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='アップロード者')),
            ],
            options={
                'verbose_name': '承認PDF',
                'verbose_name_plural': '承認PDF',
                'ordering': ['-year_month'],
                'unique_together': {('year_month',)},
            },
        ),
    ]