# Generated by Django 4.2.7 on 2025-10-10 03:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.IntegerField(unique=True, verbose_name='商品番号')),
                ('livestock_type', models.CharField(max_length=50, verbose_name='畜種')),
                ('category', models.CharField(max_length=100, verbose_name='分類')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='メーカー')),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名')),
                ('model_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='型式')),
                ('specification', models.CharField(blank=True, max_length=100, null=True, verbose_name='規格')),
                ('shipping_unit', models.CharField(max_length=50, verbose_name='発送単位')),
                ('shipping_fee', models.CharField(blank=True, max_length=100, null=True, verbose_name='送料')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('is_active', models.BooleanField(default=True, help_text='無効にすると論理削除されます', verbose_name='有効')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '商品マスタ',
                'verbose_name_plural': '商品マスタ',
                'ordering': ['product_number'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.IntegerField(help_text='2025年度 = 2025/04～2026/03', verbose_name='年度')),
                ('effective_year_month', models.CharField(help_text='YYYY/MM形式', max_length=7, verbose_name='適用年月')),
                ('end_year_month', models.CharField(blank=True, help_text='YYYY/MM形式', max_length=7, null=True, verbose_name='終了年月')),
                ('gross_margin_rate', models.DecimalField(decimal_places=6, help_text='前年度最終県連価格÷年度初め仕切価格（年度初めに1度計算、年度中は固定）', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='粗利率')),
                ('wholesale_price', models.CharField(help_text='メーカーからの仕入価格（"都度見積"等の文字列含む）', max_length=50, verbose_name='仕切価格')),
                ('kenren_price', models.CharField(blank=True, help_text='nullなら粗利率×仕切価格で自動計算、値があるならその値を表示（"都度見積"等の文字列含む）', max_length=50, null=True, verbose_name='県連価格')),
                ('retail_price', models.CharField(blank=True, help_text='一般商流での参考価格（"オープン"等の文字列含む）', max_length=50, null=True, verbose_name='参考小売価格')),
                ('revision_amount', models.DecimalField(decimal_places=0, default=0, help_text='県連価格の前月からの変動額', max_digits=12, verbose_name='改定額')),
                ('revision_reason', models.TextField(blank=True, null=True, verbose_name='改定理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_histories', to='products_master.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '価格改定履歴',
                'verbose_name_plural': '価格改定履歴',
                'ordering': ['-effective_year_month', 'product__product_number'],
                'indexes': [models.Index(fields=['period_year', 'product'], name='products_ma_period__d32120_idx')],
                'unique_together': {('product', 'effective_year_month')},
            },
        ),
    ]
