# Generated by Django 5.2.9 on 2026-01-21 09:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分類名')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '分類マスタ',
                'verbose_name_plural': '分類マスタ',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LivestockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='畜種名')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '畜種マスタ',
                'verbose_name_plural': '畜種マスタ',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='メーカー名')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'メーカーマスタ',
                'verbose_name_plural': 'メーカーマスタ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.IntegerField(default=-999, help_text='元になった商品マスタのpk（新規の場合は負の値）', verbose_name='元商品のpk')),
                ('product_code', models.CharField(blank=True, help_text='ユーザー管理用の商品コード', max_length=50, null=True, verbose_name='商品コード')),
                ('livestock_type', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='畜種')),
                ('category', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='分類')),
                ('manufacturer', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='メーカー')),
                ('product_name', models.CharField(default='', max_length=200, verbose_name='商品名')),
                ('model_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='型式')),
                ('specification', models.CharField(blank=True, max_length=100, null=True, verbose_name='規格')),
                ('shipping_unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='発送単位')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('applicant', models.CharField(blank=True, default='system', max_length=100, null=True, verbose_name='申請者')),
                ('status', models.CharField(default='申請中', max_length=20, verbose_name='ステータス')),
                ('approver', models.CharField(blank=True, max_length=100, null=True, verbose_name='承認者')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '商品マスタ承認',
                'verbose_name_plural': '商品マスタ承認',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(help_text='YYYY/MM形式', max_length=7, verbose_name='対象年月')),
                ('pdf_file_path', models.CharField(max_length=500, verbose_name='PDFファイルパス')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('uploaded_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='アップロード者')),
            ],
            options={
                'verbose_name': '承認PDF',
                'verbose_name_plural': '承認PDF',
                'ordering': ['-year_month'],
                'unique_together': {('year_month',)},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, help_text='ユーザー管理用の商品コード', max_length=50, null=True, verbose_name='商品コード')),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名')),
                ('model_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='型式')),
                ('specification', models.CharField(blank=True, max_length=100, null=True, verbose_name='規格')),
                ('shipping_unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='発送単位')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('sort_num', models.IntegerField(default=0, help_text='畜種・分類・メーカー内での連番', verbose_name='表示順序')),
                ('bigram_keywords', models.TextField(blank=True, help_text='JSON形式の2-gramキーワードリスト', null=True, verbose_name='2-gramキーワード')),
                ('applicant', models.CharField(blank=True, max_length=100, null=True, verbose_name='申請者')),
                ('status', models.CharField(choices=[('', '申請なし'), ('申請中', '申請中')], default='', max_length=20, verbose_name='ステータス')),
                ('approver', models.CharField(blank=True, max_length=100, null=True, verbose_name='承認者')),
                ('is_active', models.BooleanField(default=True, help_text='無効にすると論理削除されます', verbose_name='有効')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products_master.category', verbose_name='分類')),
                ('livestock_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products_master.livestocktype', verbose_name='畜種')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products_master.manufacturer', verbose_name='メーカー')),
            ],
            options={
                'verbose_name': '商品マスタ',
                'verbose_name_plural': '商品マスタ',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistoryApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.IntegerField(default=2025, help_text='2025年度 = 2025/04～2026/03', verbose_name='年度')),
                ('effective_year_month', models.CharField(default='2025/01', help_text='YYYY/MM形式', max_length=7, verbose_name='適用年月')),
                ('gross_margin_rate', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.90'), max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='粗利率')),
                ('wholesale_price', models.CharField(blank=True, default='都度見積', max_length=50, null=True, verbose_name='仕切価格')),
                ('kenren_price', models.CharField(blank=True, max_length=50, null=True, verbose_name='県連価格')),
                ('retail_price', models.CharField(blank=True, max_length=50, null=True, verbose_name='参考小売価格')),
                ('shipping_fee', models.CharField(blank=True, help_text='送料情報', max_length=100, null=True, verbose_name='送料')),
                ('revision_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='改定額')),
                ('revision_reason', models.TextField(blank=True, null=True, verbose_name='改定理由')),
                ('memo', models.TextField(blank=True, help_text='作業者と申請者間のコミュニケーション用', null=True, verbose_name='メモ')),
                ('is_delete_request', models.BooleanField(default=False, help_text='この履歴を削除する申請かどうか', verbose_name='削除申請')),
                ('applicant', models.CharField(blank=True, default='system', max_length=100, null=True, verbose_name='申請者')),
                ('status', models.CharField(default='申請中', max_length=20, verbose_name='ステータス')),
                ('approver', models.CharField(blank=True, max_length=100, null=True, verbose_name='承認者')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_histories', to='products_master.productapproval', verbose_name='商品')),
            ],
            options={
                'verbose_name': '価格改定履歴承認',
                'verbose_name_plural': '価格改定履歴承認',
                'ordering': ['-effective_year_month', 'product__pk'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.IntegerField(default=2025, help_text='2025年度 = 2025/04～2026/03', verbose_name='年度')),
                ('effective_year_month', models.CharField(default='2025/01', help_text='YYYY/MM形式', max_length=7, verbose_name='適用年月')),
                ('gross_margin_rate', models.DecimalField(decimal_places=6, default=Decimal('0.90'), help_text='前年度最終県連価格÷年度初め仕切価格（年度初めに1度計算、年度中は固定）', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='粗利率')),
                ('wholesale_price', models.CharField(default='都度見積', help_text='メーカーからの仕入価格（"都度見積"等の文字列含む）', max_length=50, verbose_name='仕切価格')),
                ('kenren_price', models.CharField(blank=True, help_text='nullなら粗利率×仕切価格で自動計算、値があるならその値を表示（"都度見積"等の文字列含む）', max_length=50, null=True, verbose_name='県連価格')),
                ('retail_price', models.CharField(blank=True, help_text='一般商流での参考価格（"オープン"等の文字列含む）', max_length=50, null=True, verbose_name='参考小売価格')),
                ('shipping_fee', models.CharField(blank=True, help_text='送料情報', max_length=100, null=True, verbose_name='送料')),
                ('revision_amount', models.DecimalField(decimal_places=0, default=0, help_text='非使用：get_revision_amount()で動的計算', max_digits=12, verbose_name='改定額')),
                ('revision_reason', models.TextField(blank=True, null=True, verbose_name='改定理由')),
                ('memo', models.TextField(blank=True, help_text='作業者と申請者間のコミュニケーション用', null=True, verbose_name='メモ')),
                ('applicant', models.CharField(blank=True, max_length=100, null=True, verbose_name='申請者')),
                ('status', models.CharField(choices=[('申請なし', '申請なし'), ('申請中', '申請中')], default='申請なし', max_length=20, verbose_name='ステータス')),
                ('approver', models.CharField(blank=True, max_length=100, null=True, verbose_name='承認者')),
                ('is_active', models.BooleanField(default=True, help_text='無効にすると論理削除されます', verbose_name='有効')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_histories', to='products_master.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '価格改定履歴',
                'verbose_name_plural': '価格改定履歴',
                'ordering': ['-effective_year_month', 'product__pk'],
                'indexes': [models.Index(fields=['period_year', 'product'], name='products_ma_period__d32120_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductGrossMarginRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.IntegerField(default=2025, help_text='2025年度 = 2025/04～2026/03', verbose_name='年度')),
                ('gross_margin_rate', models.DecimalField(decimal_places=6, default=Decimal('0.90'), help_text='県連価格÷仕切価格', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='粗利率')),
                ('base_kenren_price', models.DecimalField(blank=True, decimal_places=0, help_text='粗利率算定に使用した県連価格', max_digits=12, null=True, verbose_name='算定基準県連価格')),
                ('base_wholesale_price', models.DecimalField(blank=True, decimal_places=0, help_text='粗利率算定に使用した仕切価格', max_digits=12, null=True, verbose_name='算定基準仕切価格')),
                ('calculation_note', models.TextField(blank=True, help_text='粗利率の算定根拠や備考', null=True, verbose_name='算定メモ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gross_margin_rates', to='products_master.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品別年度別粗利率',
                'verbose_name_plural': '商品別年度別粗利率',
                'ordering': ['product', '-period_year'],
                'indexes': [models.Index(fields=['product', 'period_year'], name='products_ma_product_46eb79_idx')],
                'unique_together': {('product', 'period_year')},
            },
        ),
    ]
