# Generated by Django 4.2.7 on 2025-10-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='無効にすると論理削除されます', verbose_name='有効'),
        ),
    ]
