# Generated by Django 5.2.13 on 2026-06-12 07:26

import dashboard.products_master.ai_extract_models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIExtractTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True, verbose_name='トランザクションID')),
                ('executor', models.CharField(max_length=100, verbose_name='実行者')),
                ('effective_year_month', models.CharField(max_length=7, verbose_name='適用年月')),
                ('revision_reason', models.TextField(blank=True, null=True, verbose_name='改定理由')),
                ('remarks', models.CharField(blank=True, help_text='処理名やメモ', max_length=200, null=True, verbose_name='備考')),
                ('uploaded_pdf', models.FileField(blank=True, null=True, upload_to=dashboard.products_master.ai_extract_models.ai_extract_pdf_upload_path, verbose_name='アップロードPDF')),
                ('total_products', models.IntegerField(default=0, verbose_name='対象商品数')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功件数')),
                ('skip_count', models.IntegerField(default=0, verbose_name='スキップ件数')),
                ('status', models.CharField(default='完了', max_length=20, verbose_name='ステータス')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='実行日時')),
            ],
            options={
                'verbose_name': 'AI価格抽出トランザクション',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIExtractTransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(verbose_name='連番')),
                ('extracted_product_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='AI抽出商品名')),
                ('extracted_model_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='AI抽出型式')),
                ('extracted_manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='AI抽出メーカー')),
                ('extracted_specification', models.CharField(blank=True, max_length=100, null=True, verbose_name='AI抽出規格')),
                ('extracted_price', models.CharField(blank=True, max_length=50, null=True, verbose_name='AI抽出仕切価格')),
                ('extracted_retail_price', models.CharField(blank=True, max_length=50, null=True, verbose_name='AI抽出標準小売価格')),
                ('extracted_kenren_price', models.CharField(blank=True, max_length=50, null=True, verbose_name='AI抽出県連価格')),
                ('extracted_shipping_fee', models.CharField(blank=True, max_length=50, null=True, verbose_name='AI抽出送料')),
                ('extracted_gross_margin', models.CharField(blank=True, max_length=50, null=True, verbose_name='AI抽出粗利率')),
                ('extracted_revision_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='AI抽出改定理由')),
                ('match_score', models.IntegerField(blank=True, null=True, verbose_name='一致率')),
                ('selected_candidate_text', models.CharField(blank=True, max_length=300, null=True, verbose_name='選択した候補表示文字列')),
                ('status', models.CharField(max_length=20, verbose_name='処理結果')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='エラーメッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('created_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products_master.productapproval')),
                ('matched_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products_master.product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='products_master.aiextracttransaction')),
            ],
            options={
                'verbose_name': 'AI価格抽出トランザクション明細',
                'ordering': ['sequence'],
            },
        ),
    ]
