# Generated by Django 4.2.7 on 2025-10-10 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_master', '0002_pricehistory_deleted_at_pricehistory_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricehistory',
            unique_together=set(),
        ),
    ]
