# Generated by Django 5.2.13 on 2026-07-14 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_master', '0002_aiextracttransaction_aiextracttransactiondetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiextracttransactiondetail',
            name='extracted_gross_margin',
        ),
        migrations.RemoveField(
            model_name='aiextracttransactiondetail',
            name='extracted_kenren_price',
        ),
        migrations.RemoveField(
            model_name='aiextracttransactiondetail',
            name='extracted_shipping_fee',
        ),
    ]
