# Generated by Django 4.2.7 on 2025-10-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_master', '0003_alter_pricehistory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, help_text='ユーザー管理用の商品コード', max_length=50, null=True, verbose_name='商品コード'),
        ),
    ]
