# Generated by Django 4.2.7 on 2025-10-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_master', '0004_product_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_number',
            field=models.IntegerField(help_text='システム自動採番の商品番号', unique=True, verbose_name='商品番号'),
        ),
    ]
