# Generated by Django 4.2.7 on 2025-10-10 11:25

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_master', '0005_alter_product_product_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.IntegerField(help_text='システム自動採番の商品番号', verbose_name='商品番号')),
                ('product_code', models.CharField(blank=True, help_text='ユーザー管理用の商品コード', max_length=50, null=True, verbose_name='商品コード')),
                ('livestock_type', models.CharField(max_length=50, verbose_name='畜種')),
                ('category', models.CharField(max_length=100, verbose_name='分類')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='メーカー')),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名')),
                ('model_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='型式')),
                ('specification', models.CharField(blank=True, max_length=100, null=True, verbose_name='規格')),
                ('shipping_unit', models.CharField(max_length=50, verbose_name='発送単位')),
                ('shipping_fee', models.CharField(blank=True, max_length=100, null=True, verbose_name='送料')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '商品マスタ承認',
                'verbose_name_plural': '商品マスタ承認',
                'ordering': ['product_number'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistoryApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.IntegerField(help_text='2025年度 = 2025/04～2026/03', verbose_name='年度')),
                ('effective_year_month', models.CharField(help_text='YYYY/MM形式', max_length=7, verbose_name='適用年月')),
                ('end_year_month', models.CharField(blank=True, help_text='YYYY/MM形式', max_length=7, null=True, verbose_name='終了年月')),
                ('gross_margin_rate', models.DecimalField(decimal_places=6, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='粗利率')),
                ('wholesale_price', models.CharField(max_length=50, verbose_name='仕切価格')),
                ('kenren_price', models.CharField(blank=True, max_length=50, null=True, verbose_name='県連価格')),
                ('retail_price', models.CharField(blank=True, max_length=50, null=True, verbose_name='参考小売価格')),
                ('revision_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='改定額')),
                ('revision_reason', models.TextField(blank=True, null=True, verbose_name='改定理由')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_histories', to='products_master.productapproval', verbose_name='商品')),
            ],
            options={
                'verbose_name': '価格改定履歴承認',
                'verbose_name_plural': '価格改定履歴承認',
                'ordering': ['-effective_year_month', 'product__product_number'],
            },
        ),
    ]
