# Generated by Django 4.2.7 on 2025-10-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_master', '0006_productapproval_pricehistoryapproval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricehistory',
            name='end_year_month',
        ),
        migrations.RemoveField(
            model_name='pricehistoryapproval',
            name='end_year_month',
        ),
    ]
