# Generated by Django 4.2.7 on 2025-10-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_master', '0007_remove_pricehistory_end_year_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_number',
            field=models.IntegerField(blank=True, help_text='システム自動採番の商品番号', null=True, unique=True, verbose_name='商品番号'),
        ),
    ]
