# Generated by Django 4.2.7 on 2025-10-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_master', '0008_alter_product_product_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='applicant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='申請者'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='approver',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='承認者'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='status',
            field=models.CharField(choices=[('申請なし', '申請なし'), ('申請中', '申請中')], default='申請なし', max_length=20, verbose_name='ステータス'),
        ),
        migrations.AddField(
            model_name='pricehistoryapproval',
            name='applicant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='申請者'),
        ),
        migrations.AddField(
            model_name='pricehistoryapproval',
            name='approver',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='承認者'),
        ),
        migrations.AddField(
            model_name='pricehistoryapproval',
            name='status',
            field=models.CharField(default='申請中', max_length=20, verbose_name='ステータス'),
        ),
        migrations.AddField(
            model_name='product',
            name='applicant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='申請者'),
        ),
        migrations.AddField(
            model_name='product',
            name='approver',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='承認者'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('申請なし', '申請なし'), ('申請中', '申請中')], default='申請なし', max_length=20, verbose_name='ステータス'),
        ),
        migrations.AddField(
            model_name='productapproval',
            name='applicant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='申請者'),
        ),
        migrations.AddField(
            model_name='productapproval',
            name='approver',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='承認者'),
        ),
        migrations.AddField(
            model_name='productapproval',
            name='status',
            field=models.CharField(default='申請中', max_length=20, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='revision_amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='非使用：get_revision_amount()で動的計算', max_digits=12, verbose_name='改定額'),
        ),
    ]
