# Generated by Django 4.2.7 on 2025-10-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_master', '0009_pricehistory_applicant_pricehistory_approver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('', '申請なし'), ('申請中', '申請中')], default='', max_length=20, verbose_name='ステータス'),
        ),
    ]
