# Generated by Django 4.2.7 on 2025-10-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_master', '0010_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='分類'),
        ),
        migrations.AlterField(
            model_name='product',
            name='livestock_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='畜種'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='メーカー'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='発送単位'),
        ),
        migrations.AlterField(
            model_name='productapproval',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='分類'),
        ),
        migrations.AlterField(
            model_name='productapproval',
            name='livestock_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='畜種'),
        ),
        migrations.AlterField(
            model_name='productapproval',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='メーカー'),
        ),
        migrations.AlterField(
            model_name='productapproval',
            name='shipping_unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='発送単位'),
        ),
    ]
