# Generated by Django 4.2.7 on 2025-10-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_master', '0011_alter_product_category_alter_product_livestock_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistoryapproval',
            name='is_delete_request',
            field=models.BooleanField(default=False, help_text='この履歴を削除する申請かどうか', verbose_name='削除申請'),
        ),
    ]
