# Generated by Django 4.2.7 on 2025-10-16 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_master', '0012_pricehistoryapproval_is_delete_request'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS approvals_changerequest;",
            reverse_sql="-- 復元不可"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS approvals_approvalhistory;",
            reverse_sql="-- 復元不可"
        ),
    ]
