# Generated by Django 4.2.7 on 2025-10-23 08:54

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_master', '0013_auto_20251016_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistoryapproval',
            name='gross_margin_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='粗利率'),
        ),
        migrations.AlterField(
            model_name='pricehistoryapproval',
            name='wholesale_price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='仕切価格'),
        ),
    ]
