# Generated by Django 4.2.7 on 2025-10-24 05:02

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_master', '0014_alter_pricehistoryapproval_gross_margin_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGrossMarginRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.IntegerField(help_text='2025年度 = 2025/04～2026/03', verbose_name='年度')),
                ('gross_margin_rate', models.DecimalField(decimal_places=6, help_text='県連価格÷仕切価格', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='粗利率')),
                ('base_kenren_price', models.DecimalField(blank=True, decimal_places=0, help_text='粗利率算定に使用した県連価格', max_digits=12, null=True, verbose_name='算定基準県連価格')),
                ('base_wholesale_price', models.DecimalField(blank=True, decimal_places=0, help_text='粗利率算定に使用した仕切価格', max_digits=12, null=True, verbose_name='算定基準仕切価格')),
                ('calculation_note', models.TextField(blank=True, help_text='粗利率の算定根拠や備考', null=True, verbose_name='算定メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gross_margin_rates', to='products_master.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品別年度別粗利率',
                'verbose_name_plural': '商品別年度別粗利率',
                'ordering': ['product', '-period_year'],
                'indexes': [models.Index(fields=['product', 'period_year'], name='products_ma_product_46eb79_idx')],
                'unique_together': {('product', 'period_year')},
            },
        ),
    ]
