# Generated by Django 4.2.7 on 2025-11-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_master', '0016_aiextracttransaction_aiextracttransactiondetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiextracttransactiondetail',
            name='selected_candidate_text',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='選択した候補表示文字列'),
        ),
    ]
