# Generated by Django 4.2.7 on 2025-11-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_master', '0017_aiextracttransactiondetail_selected_candidate_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bigram_keywords',
            field=models.TextField(blank=True, help_text='JSON形式の2-gramキーワードリスト', null=True, verbose_name='2-gramキーワード'),
        ),
    ]
