# Generated by Django 4.2.7 on 2025-11-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_master', '0018_product_bigram_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiextracttransaction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='削除日時'),
        ),
        migrations.AddField(
            model_name='aiextracttransaction',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='有効'),
        ),
    ]
