# Generated by Django 5.2.7 on 2025-11-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_master', '0019_aiextracttransaction_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiextracttransaction',
            name='remarks',
            field=models.CharField(blank=True, help_text='処理名やメモ', max_length=200, null=True, verbose_name='備考'),
        ),
    ]
