# Generated by Django 5.2.7 on 2025-11-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_master', '0020_aiextracttransaction_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiextracttransactiondetail',
            name='extracted_revision_reason',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='AI抽出改定理由'),
        ),
    ]
