# Generated by Django 5.2.7 on 2025-11-28 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_master', '0021_aiextracttransactiondetail_extracted_revision_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['-effective_year_month', 'product__pk'], 'verbose_name': '価格改定履歴', 'verbose_name_plural': '価格改定履歴'},
        ),
        migrations.AlterModelOptions(
            name='pricehistoryapproval',
            options={'ordering': ['-effective_year_month', 'product__pk'], 'verbose_name': '価格改定履歴承認', 'verbose_name_plural': '価格改定履歴承認'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['pk'], 'verbose_name': '商品マスタ', 'verbose_name_plural': '商品マスタ'},
        ),
        migrations.AlterModelOptions(
            name='productapproval',
            options={'ordering': ['pk'], 'verbose_name': '商品マスタ承認', 'verbose_name_plural': '商品マスタ承認'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_number',
        ),
        migrations.RemoveField(
            model_name='productapproval',
            name='product_number',
        ),
    ]
