# Generated by Django 5.2.7 on 2025-11-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_master', '0022_alter_pricehistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productapproval',
            name='product_number',
            field=models.IntegerField(default=-999, help_text='元になった商品マスタのpk（新規の場合は負の値）', verbose_name='元商品のpk'),
        ),
    ]
