# Generated by Django 5.2.7 on 2025-12-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_master', '0023_productapproval_product_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sort_num',
            field=models.IntegerField(default=0, help_text='畜種・分類・メーカー内での連番', verbose_name='表示順序'),
        ),
    ]
