# Generated by Django 5.2.7 on 2025-12-03 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_master', '0026_add_manufacturer_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products_master.manufacturer', verbose_name='メーカー'),
        ),
        migrations.CreateModel(
            name='ApprovalPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(help_text='YYYY/MM形式', max_length=7, verbose_name='対象年月')),
                ('pdf_file_path', models.CharField(max_length=500, verbose_name='PDFファイルパス')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('uploaded_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='アップロード者')),
            ],
            options={
                'verbose_name': '承認PDF',
                'verbose_name_plural': '承認PDF',
                'ordering': ['-year_month'],
                'unique_together': {('year_month',)},
            },
        ),
    ]
