"""
Django settings for digital_pricelist_system project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
import configparser
from dotenv import load_dotenv

# .envファイルを読み込み
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 設定ファイルパス（一箇所で定義）
CONFIG_PATH = Path(r"\\128.167.100.10\資材・大家畜事業部\04資材部\★デジタル価格表作成プログラム\config.ini")

def get_config():
    """設定ファイルを読み込み"""
    config = configparser.ConfigParser()
    
    if CONFIG_PATH.exists():
        try:
            config.read(CONFIG_PATH, encoding='utf-8')
            return config
        except Exception:
            pass
    
    return None

def get_database_path():
    """データベースパスを取得"""
    # 環境変数から取得（Django_run.pyから設定）
    if 'DATABASE_PATH' in os.environ:
        return os.environ['DATABASE_PATH']
    
    # config.iniから直接読み込み
    config = configparser.ConfigParser()
    if CONFIG_PATH.exists():
        try:
            config.read(CONFIG_PATH, encoding='utf-8')
            db_path = config.get('DATABASE', 'path', fallback='db.sqlite3')
            # 絶対パスか相対パスか判定
            if os.path.isabs(db_path):
                return db_path
            else:
                # PyInstaller環境では相対パスをexeフォルダからの相対パスとして解釈
                if getattr(sys, 'frozen', False):
                    exe_dir = Path(sys.executable).parent
                    return str(exe_dir / db_path)
                else:
                    return str(BASE_DIR / db_path)
        except Exception:
            pass
    
    # デフォルト
    if getattr(sys, 'frozen', False):
        return str(Path(sys.executable).parent / 'db.sqlite3')
    return str(BASE_DIR / 'db.sqlite3')

def get_media_root():
    """メディアファイル保存先を取得"""
    config = configparser.ConfigParser()
    if CONFIG_PATH.exists():
        try:
            config.read(CONFIG_PATH, encoding='utf-8')
            media_path = config.get('FILES', 'media_root', fallback='media')
            # 絶対パスか相対パスか判定
            if os.path.isabs(media_path):
                return Path(media_path)
            else:
                # PyInstaller環境では相対パスをexeフォルダからの相対パスとして解釈
                if getattr(sys, 'frozen', False):
                    exe_dir = Path(sys.executable).parent
                    return exe_dir / media_path
                else:
                    return BASE_DIR / media_path
        except Exception:
            pass
    
    # デフォルト
    if getattr(sys, 'frozen', False):
        return Path(sys.executable).parent / 'media'
    return BASE_DIR / 'media'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-cu8ryq2pn^2_oc(-852@nyb6#3@+fmz@c^yy4+_8+pv#mvx@vl')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard.products_master',
    'system_admin',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'digital_pricelist_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'digital_pricelist_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': get_database_path(),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = get_media_root()

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024   # 10MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000  # AI抽出で大量のフィールドが送信される場合に対応

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
