# Generated by Django 4.2.7 on 2025-10-10 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('CREATE', '新規作成'), ('UPDATE', '更新'), ('DELETE', '削除')], max_length=10, verbose_name='申請種別')),
                ('status', models.CharField(choices=[('PENDING', '申請中'), ('APPROVED', '承認済み'), ('REJECTED', '却下'), ('CANCELLED', '取り消し')], default='PENDING', max_length=10, verbose_name='ステータス')),
                ('requester', models.CharField(help_text='username@hostname形式', max_length=100, verbose_name='申請者')),
                ('approver', models.CharField(blank=True, help_text='username@hostname形式', max_length=100, null=True, verbose_name='承認者')),
                ('request_data', models.JSONField(help_text='変更内容をJSON形式で保存', verbose_name='申請データ')),
                ('source_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='元PDFファイル')),
                ('ai_extracted', models.BooleanField(default=False, verbose_name='AI抽出')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='申請日時')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='処理日時')),
                ('request_comment', models.TextField(blank=True, null=True, verbose_name='申請コメント')),
                ('approval_comment', models.TextField(blank=True, null=True, verbose_name='承認コメント')),
                ('target_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products_master.product', verbose_name='対象商品')),
            ],
            options={
                'verbose_name': '変更申請',
                'verbose_name_plural': '変更申請',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver', models.CharField(help_text='username@hostname形式', max_length=100, verbose_name='承認者')),
                ('action', models.CharField(choices=[('APPROVE', '承認'), ('REJECT', '却下'), ('REQUEST_CHANGE', '修正依頼')], max_length=20, verbose_name='アクション')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='コメント')),
                ('processed_at', models.DateTimeField(auto_now_add=True, verbose_name='処理日時')),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_histories', to='approvals.changerequest', verbose_name='変更申請')),
            ],
            options={
                'verbose_name': '承認履歴',
                'verbose_name_plural': '承認履歴',
                'ordering': ['-processed_at'],
            },
        ),
    ]
